# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: MyGitHubRepo
      type: github
      endpoint: WickramBug
      name: WickramBug/acr-purge
      ref: main

jobs:
  - job: LockACRImage
    displayName: "Lock prod ACR image"
    steps:
      - checkout: MyGitHubRepo
        persistCredentials: true
      # TEST FAILED ALERT
      # - script: |
      #     cat pipelines/chat-notify.yml
      #   workingDirectory: alert-test
      # TEST FAILED ALERT
      - task: AzureCLI@2
        inputs:
          azureSubscription: "sre-rnd-001(fa56d6cf-aca8-41c3-8883-0720a2835276)"
          scriptType: "bash"
          scriptLocation: "scriptPath"
          scriptPath: "$(Build.SourcesDirectory)/acr-write-state-file.sh"
          arguments: "wickramContainerRegistry001 hi_mom_nginx sha256:169507c43862fec30cda7b4a6c6e66a4a99f5d9fd19ff5bb1ca5adca79678996"
        displayName: "Lock ACR Images"
      - task: CmdLine@2
        inputs:
          script: |
            git -C $(Agent.BuildDirectory)/ config user.email "wickram95@gmail.com"
            git -C $(Agent.BuildDirectory)/ config user.name "WickramBug"
            git -C $(Agent.BuildDirectory)/ checkout main
            git -C $(Agent.BuildDirectory)/ pull origin main
            git -C $(Agent.BuildDirectory)/ add $(Agent.BuildDirectory)/acr-image-state.txt
            git -C $(Agent.BuildDirectory)/ commit -m "[Prod] Update state file via pipeline for the latest build - $(Build.SourceBranchName)"
            git -C $(Agent.BuildDirectory)/ push origin main
            echo "[Prod] State file update is completed!"
        displayName: "Push updated state file to Repo"
  - job: SendingAlert
    displayName: "Sending Google chat alert"
    dependsOn:
      - LockACRImage
    condition: eq(dependencies.LockACRImage.result, 'Failed')
    steps:
      - template: "alerts/send-alert-acr-image-lock.yaml"
        parameters:
          PIPELINE_NAME: "Asgardeo ACR Image Lock"
          ENVIRONMENT: "PROD"
          PIPELINE_STATUS: "Failed"
          GOOGLE_CHAT_SPACE: "AAAA-y5RxXY"
          GOOGLE_CHAT_KEY: "AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI"
          GOOGLE_CHAT_TOKEN: "n678xyeVxt1ZXmw052hT_4pgJIm1BNSNE-iYDf0AgZY%3D"
