# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: MyGitHubRepo
    type: github
    endpoint: WickramBug
    name: WickramBug/acr-purge
    ref: main
  
steps:
- checkout: MyGitHubRepo
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sre-rnd-001(fa56d6cf-aca8-41c3-8883-0720a2835276)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)/acr-write-state-file.sh'
  displayName: "Write state file"
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "wickram95@gmail.com"
      git config --global user.name "WickramBug"
      git branch
      echo "Git Status -------------------------------"
      git status
      echo "Git Status -------------------------------"
      git add .
      git commit -m "Modify state file"
      git pull origin main
      git push origin main
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sre-rnd-001(fa56d6cf-aca8-41c3-8883-0720a2835276)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)/acr-retention.sh'
  displayName: "Run purge script"
