# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: MyGitHubRepo
      type: github
      endpoint: WickramBug
      name: WickramBug/acr-purge
      ref: main

jobs:
  - job: LockACRImage
    displayName: "Lock prod ACR image"
    steps:
      - checkout: MyGitHubRepo
        persistCredentials: true
      # TEST FAILED ALERT
      # - script: |
      #     cat pipelines/chat-notify.yml
      #   workingDirectory: alert-test
      # TEST FAILED ALERT
      - task: AzureCLI@2
        inputs:
          azureSubscription: "sre-rnd-001(fa56d6cf-aca8-41c3-8883-0720a2835276)"
          scriptType: "bash"
          scriptLocation: "scriptPath"
          scriptPath: "$(Build.SourcesDirectory)/acr-write-state-file.sh"
        displayName: "Write state file"
      - task: CmdLine@2
        inputs:
          script: |
            git config --global user.email "wickram95@gmail.com"
            git config --global user.name "WickramBug"
            git checkout main
            git add .
            git commit -m "Update state file via pipeline"
            git pull origin main
            git push
        displayName: "Push updated state file to Repo"
      - task: AzureCLI@2
        inputs:
          azureSubscription: "sre-rnd-001(fa56d6cf-aca8-41c3-8883-0720a2835276)"
          scriptType: "bash"
          scriptLocation: "scriptPath"
          scriptPath: "$(Build.SourcesDirectory)/acr-lock-image.sh"
        displayName: "Run image lock script"
  - job: SendingAlert
    displayName: "Sending Google chat alert"
    dependsOn:
      - LockACRImage
    condition: eq(dependencies.LockACRImage.result, 'Failed')
    steps:
      - template: "alerts/send-alert-acr-image-lock.yaml"
        parameters:
          PIPELINE_NAME: "Asgardeo ACR Image Lock"
          ENVIRONMENT: "prod"
          PIPELINE_STATUS: "Failed"
          GOOGLE_CHAT_SPACE: "AAAA-y5RxXY"
          GOOGLE_CHAT_KEY: "AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI"
          GOOGLE_CHAT_TOKEN: "n678xyeVxt1ZXmw052hT_4pgJIm1BNSNE-iYDf0AgZY%3D"
